### ISSUE TITLE
ploz halp senpai 

### ISSUE THREAD

**Issue by TALON56** [LuckehPickle/Comet#4]
is:issue is:open i m get tha kik for the namerino, admin abuse plox. kik from server punkbuster op

**Comment by LuckehPickle** [comment]
ķ̶̦̩̤̟̟̰̝͚̭̥̘͖͈̮̩͒̓̌͒͜.̋ͯ͛ͫ͒̚͘҉̷̝̙̩͈̟͈̲̪͢͡ͅ
